package com.example.cv.Controller;

import com.example.cv.dao.CVDao;
import com.example.cv.model.CVmodel;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import javax.lang.model.element.Name;
import java.io.File;

public class CVcontroller {
    @FXML
    TextField name;
    @FXML
    TextField email;
    @FXML
    TextField phone;
    @FXML
    TextField address;
    @FXML
    TextField education;
    @FXML
    TextField skills;
    @FXML
    TextField worksExperience;
    @FXML
    TextField projects;
    @FXML
    ImageView previewImage;

    private String imagePath; // store selected image
    private final CVDao cvDao = new CVDao();
    // ------------------------ UPLOAD IMAGE BUTTON ------------------------
    @FXML
    private void onChooseImageClicked(ActionEvent event) {
        FileChooser chooser = new FileChooser();
        chooser.setTitle("Choose Profile Image");
        File file = chooser.showOpenDialog(getStage());
        if (file != null) {
            imagePath = file.getAbsolutePath();
        }
    }
    @FXML
    private void GenerateCV(ActionEvent event) throws Exception {



        if (name.getText().isBlank()) {
            showAlert("Validation", "Name is required.");
            return;
        }
        String Name = name.getText();
        String Email = email.getText();
        String Phone = phone.getText();
        String Address = address.getText();
        String Education = education.getText();
        String Skills = skills.getText();
        String WorksExperience = worksExperience.getText();
        String Projects = projects.getText();

        CVmodel cv = new CVmodel(
                0, // id auto-generated by DB
                Name,
                Email,
                Phone,
                Address,
                Education,
                Skills,
                WorksExperience,
                Projects,
                imagePath
        );

        cvDao.insert(cv);
        showAlert("Success", "CV saved.");
        clearForm();



        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/CVlist.fxml"));
        Parent root = loader.load();

        // Pass data to second controller
       // CVviewController controller = loader.getController();
      //  controller.setData(Name,Phone,Email,Address,Education,Skills,WorksExperience,Projects,imagePath);
        Stage stage = (Stage) ((javafx.scene.Node) event.getSource()).getScene().getWindow();

        Scene scene = new Scene(root, 800, 800);
        stage.setScene(scene);
        stage.show();

    }
    private Stage getStage() {
        return (Stage) name.getScene().getWindow();
    }
    private void clearForm() {
        name.clear();
        email.clear();
        phone.clear();
        address.clear();
        education.clear();
        skills.clear();
        worksExperience.clear();
        projects.clear();
        imagePath = null;
    }

    private void showAlert(String title, String msg) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(msg);
        alert.showAndWait();
    }

}
